repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.19.0
  hooks:
  - id: pyupgrade
    args: ["--py39-plus"]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.1
  hooks:
    - id: ruff
      args: ["--fix"]
    - id: ruff-format

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    exclude: ^(conda\.)?recipe/meta.yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: \.(cal|cov)$
  - id: mixed-line-ending
  - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v19.1.2'
  hooks:
  - id: clang-format
    files: \.(c|cc|h|hh)$
