repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v2.32.1
  hooks:
  - id: pyupgrade
    args: ["--py37-plus"]

- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.2.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-yaml
    exclude: ^(conda\.)?recipe/meta.yaml
  - id: debug-statements
  - id: end-of-file-fixer
    exclude: \.(cal|cov)$
  - id: mixed-line-ending
  - id: trailing-whitespace

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: 'v12.0.1'
  hooks:
  - id: clang-format
    files: \.(c|cc|h|hh)$
