[tool.black]
target-version = ['py37', 'py38', 'py39', 'py310', 'py311']
include = '\.pyi?$'
exclude = '''
(
  /(
      \.asv
    | \.eggs
    | \.git
    | \.venv
    | benchmarks
    | build
    | conda.recipe
    | dist
  )/
  | _version.py
  | versioneer.py
)
'''
