name: Test

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
        root-version: ['6.26.10', '6.28.12', '6.30.4', '6.32.2']
        exclude:
          - python-version: '3.12'
            root-version: '6.26.10'
          - python-version: '3.12'
            root-version: '6.28.12'
          - python-version: '3.12'
            root-version: '6.30.4'
      fail-fast: false

    steps:
    - uses: actions/checkout@v2

    - name: Setup conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        miniconda-version: "latest"
        mamba-version: "*"
        channels: conda-forge
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      shell: bash -l {0}
      run: mamba install root=${{ matrix.root-version }} numpy scipy prompt_toolkit matplotlib uncertainties docutils pytest pytest-cov

    - name: Test with pytest
      shell: bash -l {0}
      run: pytest -v --color=yes --cov=hdtv --cov-report=xml tests

    - name: Post Coverage
      uses: codecov/codecov-action@v1
      if: matrix.python-version == '3.12' && matrix.root-version == '6.32.2'
